#pragma once

#define GT_CONTEXT_RSP_OFFSET 0
#define GT_CONTEXT_RBX_OFFSET 8
#define GT_CONTEXT_RBP_OFFSET 16
#define GT_CONTEXT_R12_OFFSET 24
#define GT_CONTEXT_R13_OFFSET 32
#define GT_CONTEXT_R14_OFFSET 40
#define GT_CONTEXT_R15_OFFSET 48
